#!/bin/bash

containerIDs=`docker ps -q`

if [[ -z "$containerIDs" ]]; then
	echo "No active docker containers found to stop."
else
	echo "Stopping all active docker containers."
	docker stop $containerIDs
fi

