#!/bin/bash

set -e

echo "Upgrading all packages..."
sudo apt update && sudo apt full-upgrade -y

echo "Autoremoving packages..."
sudo apt autoremove -y

echo "Cleaning packages..."
sudo apt clean -y

